// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TabHelper.Data.ORM;

namespace TabHelper.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190206002017_AddedFirstMigration")]
    partial class AddedFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TabHelper.Models.Entities.DepartFile", b =>
                {
                    b.Property<int>("DepartmentId");

                    b.Property<int>("TabulationId");

                    b.HasKey("DepartmentId", "TabulationId");

                    b.HasIndex("TabulationId");

                    b.ToTable("DepartmentTabulations");
                });

            modelBuilder.Entity("TabHelper.Models.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset?>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<DateTimeOffset?>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("TabHelper.Models.Entities.Form", b =>
                {
                    b.Property<int>("TabulationId");

                    b.Property<int>("TabulationAttributesId");

                    b.HasKey("TabulationId", "TabulationAttributesId");

                    b.HasIndex("TabulationAttributesId");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("TabHelper.Models.Entities.FormAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ComponentType");

                    b.Property<DateTimeOffset?>("CreatedAt");

                    b.Property<string>("Detail");

                    b.Property<string>("Info");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<int>("Order");

                    b.Property<string>("Title");

                    b.Property<DateTimeOffset?>("UpdatedAt");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("TabulationAttributes");
                });

            modelBuilder.Entity("TabHelper.Models.Entities.Historic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset?>("CreatedAt");

                    b.Property<string>("FormJson");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("TabulationId");

                    b.Property<DateTimeOffset?>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Historics");
                });

            modelBuilder.Entity("TabHelper.Models.Entities.Tabulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset?>("CreatedAt");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<string>("Observation");

                    b.Property<DateTimeOffset?>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Tabulations");
                });

            modelBuilder.Entity("TabHelper.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset?>("CreatedAt");

                    b.Property<int?>("DepartmentId");

                    b.Property<string>("Email");

                    b.Property<bool>("IsBlock");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<DateTimeOffset?>("UpdatedAt");

                    b.Property<int>("UserAccess");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TabHelper.Models.Entities.DepartFile", b =>
                {
                    b.HasOne("TabHelper.Models.Entities.Department", "Department")
                        .WithMany("DepartmentTabulations")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TabHelper.Models.Entities.Tabulation", "Tabulation")
                        .WithMany("DepartmentTabulations")
                        .HasForeignKey("TabulationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TabHelper.Models.Entities.Form", b =>
                {
                    b.HasOne("TabHelper.Models.Entities.FormAttribute", "TabulationAttributes")
                        .WithMany("Forms")
                        .HasForeignKey("TabulationAttributesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TabHelper.Models.Entities.Tabulation", "Tabulation")
                        .WithMany("Forms")
                        .HasForeignKey("TabulationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TabHelper.Models.Entities.User", b =>
                {
                    b.HasOne("TabHelper.Models.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId");
                });
#pragma warning restore 612, 618
        }
    }
}
